# Generated by Django 3.2 on 2022-08-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.FileField(upload_to='upload/videos'),
        ),
    ]
